spring.application.name=payment-service
server.port=8083
spring.datasource.url=jdbc:mysql://arun-rds.ccbauapvuaoz.ap-south-1.rds.amazonaws.com:3306/payment_db
spring.datasource.username=admin
spring.datasource.password=Arun1234
spring.jpa.hibernate.ddl-auto=update
spring.kafka.bootstrap-servers=
b-1.arunmskfinal.z59bv2.c2.kafka.ap-south-1.amazonaws.com:9098,
b-2.arunmskfinal.z59bv2.c2.kafka.ap-south-1.amazonaws.com:9098,
b-3.arunmskfinal.z59bv2.c2.kafka.ap-south-1.amazonaws.com:9098
# CONSUMER
spring.kafka.consumer.group-id=payment-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.example.payment_service.events.OrderCreatedEvent

# PRODUCER
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer