apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: 883178794881.dkr.ecr.ap-south-1.amazonaws.com/payment-service:v6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: b-3.aruncluster1.ddm72v.c2.kafka.ap-south-1.amazonaws.com:9098,b-2.aruncluster1.ddm72v.c2.kafka.ap-south-1.amazonaws.com:9098,b-1.aruncluster1.ddm72v.c2.kafka.ap-south-1.amazonaws.com:9098
